### ISSUE TITLE
Support for Sealed Traits

### ISSUE THREAD

**Issue by beefyhalo** [evolution-gaming/kryo-macros#1]
Hello,

Is there support for de/serialization of sealed traits?

Thanks!

**Comment by t3hnar** [comment]
Hi @beefyhalo here is an example of a `trait`
https://github.com/evolution-gaming/kryo-macros/blob/master/src/test/scala/com/evolutiongaming/kryo/SerializerMacroSpec.scala#L204

**Comment by stasimus** [comment]
Documentation is going to be updated in the scope of https://github.com/evolution-gaming/kryo-macros/issues/9
